# Generated by Django 4.2.6 on 2023-12-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('special_request', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=20)),
                ('license_pdf', models.FileField(upload_to='license_pdfs/')),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('aadhaar_pdf', models.FileField(upload_to='aadhaar_pdfs/')),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carlisting')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carowner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
