# Generated by Django 4.2.6 on 2024-02-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accessory_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compatibility', models.CharField(max_length=100)),
                ('quantity_available', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('installation_requirements', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('dimensions_weight', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(upload_to='accessory_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessory_images/')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.caraccessory')),
            ],
        ),
    ]
