# Generated by Django 4.2.6 on 2024-02-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_caraccessory_accessoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
