# Generated by Django 4.2.6 on 2024-02-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
