# Generated by Django 4.2.6 on 2024-02-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
