# Generated by Django 4.2.6 on 2024-03-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
