# Generated by Django 4.2.6 on 2024-03-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
